// The DTO contract across the preload bridge. Imported as TYPES by main
// (produces them from @terrarium/core) and renderer (draws them). Kept free of
// any Node/core import so the renderer can reference it safely.
export type Rung = 'installed' | 'running' | 'responds' | 'live'

export const RUNGS: { key: Rung; label: string }[] = [
  { key: 'installed', label: 'Installed' },
  { key: 'running', label: 'Running' },
  { key: 'responds', label: 'Responds' },
  { key: 'live', label: 'Live' },
]

export type ServiceState = 'live' | 'idle' | 'down'

export interface ServiceView {
  id: string
  name: string
  port: string
  state: ServiceState
  reachedIdx: number // -1 = nothing achieved .. 3 = live
  detail: string
}

export interface GpuView {
  name: string
  totalGb: number
  usedGb: number | null // null until we poll live usage
}

export interface MetaView {
  bot: { name: string; handle: string; live: boolean } | null
  owner: 'terrarium' | 'tasks'
  brain: string
  gpu: GpuView | null
}

export interface LogLine {
  id: number
  ts: string
  svc: string
  msg: string
  level: string
}

export interface CoreState {
  services: ServiceView[]
  meta: MetaView
}

export type ActionType = 'start' | 'stop' | 'restart' | 'restartAll' | 'migrate' | 'release'

export interface ActionRequest {
  type: ActionType
  id?: string
  label?: string // human name for the confirm dialog
}

export interface ActionResult {
  ok: boolean
  message: string
}

// ---- doctor (read-only health check) ----
export interface DoctorCheckView {
  id: string
  title: string
  status: 'ok' | 'warn' | 'fail'
  detail: string
}
export interface DoctorReportView {
  checks: DoctorCheckView[]
  healthy: boolean
}

// ---- bot builder (create a companion → full card + AGENTS.md compact card) ----
export interface BotSpecInput {
  slug: string
  displayName: string
  age: number
  look: string
  vibe: string
  loves: string
  relationship: string
  backstory: string
  speechStyle: string[]
  hardRules: string[]
  openerIdeas: string[]
  photo: { identity: string; outfit: string; shot: string }
}
export interface BotPreview {
  ok: boolean
  errors: string[]
  compactCard: string
  currentChars: number
  cardChars: number
  resultChars: number
  headroom: number
  fits: boolean
}
export interface BotCreateResult {
  ok: boolean
  errors: string[]
  wrote: boolean
  backupPath: string | null
  fullCardPath: string | null
}

// ---- brains (swap the primary model, edited in-place in openclaw.json) ----
export interface BrainOpt {
  ref: string // provider/id, e.g. arliai/Gemma-4-31B-DarkIdol
  provider: string
  id: string
  contextWindow: number | null
  reasoning: boolean
  kind: 'hosted' | 'local'
}
export interface BrainsList {
  current: string
  models: BrainOpt[]
}
// ref -> liveness. 'local' = an Ollama model (runs here); hosted probed live.
export type BrainLiveness = Record<string, 'up' | 'down' | 'local' | 'unknown'>

// ---- chat (shares agent:main:main with Telegram) ----
export interface ChatMsg {
  role: 'user' | 'assistant'
  text: string
  ts: number | null
  /**
   * terrarium:// URLs of any images on this message. Photos generated by the pic
   * daemon are mirrored into Terrarium's inbox and pushed as assistant messages
   * with these set (text = the caption, if any). Absent/empty for text messages.
   */
  images?: string[]
}

export interface ChatStatus {
  state: 'connecting' | 'ready' | 'sending' | 'closed' | 'error'
  detail: string
}

export interface ChatConnectResult {
  ok: boolean
  message?: string
  history: ChatMsg[]
}
